
services:
  db:
    image: postgres:16
    container_name: sw_final_db
    restart: always
    environment:
      POSTGRES_DB: sw_final
      POSTGRES_USER: sw
      POSTGRES_PASSWORD: sw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sw -d sw_final" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: sw_final_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sw_final
      SPRING_DATASOURCE_USERNAME: sw
      SPRING_DATASOURCE_PASSWORD: sw

volumes:
  pgdata: